import React, { useState, useEffect } from "react";
import Head from "next/head";

const NFTPage = ({ itemid }) => {
  return (
    <div>
      <Head>
        <title>NFT Page</title>
        <meta name="description" content="Generated by Collection Page" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export const getServerSideProps = async ({ query, params, req }) => {
  //find NFT ID
  //get all its info
  //render on page
  console.log(query.itemid);
  console.log(query.glb);
  console.log(query.collection);

  return {
    props: {
      // item: items.find((i) => i.name === params?.collection),
      itemid: { id: query.itemid, glb: query.glb },
    },
  };
};

export default NFTPage;
