import React, { useState } from "react";
import Head from "next/head";

import GameCard from "../../components/Cards/GameCard";

const Games = () => {
  return (
    <div className="">
      <Head>
        <title>DAM || HOME </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen flex  items-center w-full justify-evenly">
        <GameCard GameImg={`/GameIMG/`} GameId={1} GameName={"Game Name 0"} />
        <GameCard GameImg={`/GameIMG/`} GameId={1} GameName={"Game Name 0"} />
      </div>
    </div>
  );
};

export default Games;
