import React from "react";
import Head from "next/head";

import { Chat } from "@pushprotocol/uiweb";

const Chatroom = () => {
  return (
    <div>
      <Head>
        <title>DAM || Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* {renderButton()}
        {address}
        <Chat
          account={address} //user address
          supportAddress="0xf2997b416b3214BF1A41431A2B7Fa49F4b75eF8f" //support address
          apiKey="jVPMCRom1B.iDRMswdehJG7NpHDiECIHwYMMv6k2KzkPJscFIDyW8TtSnk4blYnGa8DIkfuacU0"
          env="staging"
          primaryColor="black"
        /> */}
    </div>
  );
};

export default Chatroom;
