import React from "react";
import Head from "next/head";

import { Chat } from "@pushprotocol/uiweb";

const Chatroom = () => {
  return (
    <div>
      <Head>
        <title>DAM || Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Chat
        account="0xf2997b416b3214BF1A41431A2B7Fa49F4b75eF8f" //user address
        supportAddress="0x872F28c70eD27D7B8f58cc2A9264A4414548f4fc" //support address
        apiKey="9uYRhy0hol.fDp4IHD7auZOFpNDDtz2Ql4i2W9RYj2tpA9TLWyuX4AmVIC3Ge9MtyAHJAWOB6je"
        env="staging"
        primaryColor="black"
      />
    </div>
  );
};

export default Chatroom;
