import Container from "../components/Grid/Container";
import React from "react";
import Head from "next/head";

const Chat = () => {
  return (
    <div>
      <Head>
        <title>DAM || Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <h1>Centered text</h1>
      </Container>
    </div>
  );
};

export default Chat;
