import React from "react";
import Head from "next/head";

const Ens = () => {
  return (
    <div>
      <Head>
        <title>DAM || ENS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Ens;
