import Head from "next/head";
import Games from "./games";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>DAM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Games></Games>
    </div>
  );
}
